---
title: "Emmas Wordcloud"
output: html_notebook
---
```{r}
library(tidytext)
library(dplyr)
library(RColorBrewer)
library(wordcloud2)
library(wordcloud)
library(tm)
library(text2vec)
```

```{r}
word_vec <- c("et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, et, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, odio, pellentesque, diam, volutpat, commodo, sed, egestas, egestas, fringilla, phasellus, faucibus, scelerisque, eleifend, donec, pretium, vulputate, sapien, nec, sagittis, aliquam, malesuada, bibendum, arcu, vitae, elementum, curabitur, vitae, nunc, sed, velit, dignissim, sodales, ut, eu, sem, integer, vitae, justo, eget, magna, fermentum, iaculis, eu, non, diam, phasellus, vestibulum, lorem, sed, risus, egestas, egestas, fringilla, phasellus, faucibus, scelerisque, eleifend, donec, pretium, vulputate, sapien, nec, sagittis, aliquam, malesuada, bibendum, arcu, vitae, elementum, curabitur, vitae, nunc, sed, velit, dignissim, sodales, ut, eu, sem, integer, vitae, justo, eget, magna, fermentum, iaculis, eu, non, diam, phasellus, vestibulum, lorem, sed, risus, egestas, egestas, fringilla, phasellus, faucibus, scelerisque, eleifend, donec, pretium, vulputate, sapien, nec, sagittis, aliquam, malesuada, bibendum, arcu, vitae, elementum, curabitur, vitae, nunc, sed, velit, dignissim, sodales, ut, eu, sem, integer, vitae, justo, eget, magna, fermentum, iaculis, eu, non, diam, phasellus, vestibulum, lorem, sed, risus, egestas, egestas, fringilla, phasellus, faucibus, scelerisque, eleifend, donec, pretium, vulputate, sapien, nec, sagittis, aliquam, malesuada, bibendum, arcu, vitae, elementum, curabitur, vitae, nunc, sed, velit, dignissim, sodales, ut, eu, sem, integer, vitae, justo, eget, magna, fermentum, iaculis, eu, non, diam, phasellus, vestibulum, lorem, sed, risus")

text <- tibble(words = word_vec, 
               id = 1)

words_df <- text %>%
  unnest_tokens(word, words, to_lower = FALSE) %>%
  group_by(word) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
words_df
```


```{r}
wordcloud4 <- wordcloud2(data = words_df, 
                         size = 1, 
                         color = rep_len(color, nrow(words_df)))
wordcloud4
#save
```

```{r}
color2 <- c("red", "green", "blue", "purple", "yellow", "orange")

wordcloud5 <- wordcloud2(data = words_df, 
                         size = 1, 
                         color = rep_len(color2, nrow(words_df)))
wordcloud5
#save!
```

```{r}
library(webshot)
library(htmlwidgets)
```
```{r}
saveWidget(wordcloud5, "tmp.html", selfcontained = FALSE)
webshot("tmp.html", "wordcloud5.png", delay = 5, vwidth = 480, vheight = 480)
```












```{r}
display.brewer.all()
```

```{r}

```


